"""Sample Sutra Units from BPHS into the golden fixture, for hand-checking.

The sample is deliberately biased toward the cases that break: grouped verse
ranges, vol 2's alternative danda, and units spanning a page boundary. A random
sample would be mostly easy single verses on a single page, and **a broken bridge
would pass it** — which is the one thing a gate must never do.

    uv run python -m scripts.build_golden_units --per-volume 60

The output is a STARTING POINT, not a gate. A human must read each unit against
the scanned page and correct or delete any wrong pairing before it counts as
golden: a fixture generated by the very code it tests proves only that the code is
self-consistent. Record how many units were corrected and how many deleted — that
number is the bridge's true error rate and it belongs in the pilot report.
"""

import argparse
import asyncio
import json
from pathlib import Path

from sqlalchemy import select, text

from rishivan.db.session import async_session_factory
from rishivan.knowledge.bridge.adapt import SourceRow, adapt_rows
from rishivan.knowledge.reflow import reflow_book
from rishivan.models.document import Document

OUT = Path("tests/golden/bphs_adjacency.json")
VOLUMES = ("bphs-gcsharma-vol1", "bphs-gcsharma-vol2")
TITLE = "Brihat Parasara Hora Shastra"

_DANDA_VOL2 = "।।"
"""Vol 2's delimiter. A unit containing it exercises the branch that would
otherwise silently infer 57% of vol 2's verse numbers."""


def _interest(unit) -> tuple[int, str]:
    """Sort key, highest interest first. Ties break on the ref for stability.

    Scores the risk in a unit rather than its content: a grouped range means the
    merge path ran, a page span means reflow survived a running head, and a read
    (not inferred) number means the delimiter regex actually fired.
    """
    score = 0
    if unit.verse_ref_local and "-" in unit.verse_ref_local:
        score += 3
    if unit.page_to is not None and unit.page_from != unit.page_to:
        score += 3
    if _DANDA_VOL2 in unit.verse_devanagari:
        score += 2
    if not unit.inferred_verse_no:
        score += 1
    if unit.commentary.strip():
        score += 1
    return (-score, unit.verse_ref_local or "")


async def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sample BPHS Sutra Units into the golden fixture"
    )
    parser.add_argument("--per-volume", type=int, default=60)
    args = parser.parse_args(argv)

    entries: list[dict] = []
    async with async_session_factory() as session:
        for slug in VOLUMES:
            document = await session.scalar(
                select(Document).where(Document.slug == slug)
            )
            if document is None:
                raise LookupError(f"no document with slug {slug!r}")

            rows = [
                SourceRow(*row)
                for row in (
                    await session.execute(
                        text(
                            "select id, page_number, element_index, type, content "
                            "from source_element "
                            "where document_id = :doc and deleted_at is null "
                            "order by page_number, element_index"
                        ),
                        {"doc": document.id},
                    )
                ).all()
            ]

            units = reflow_book(adapt_rows(rows, book_title=TITLE))
            complete = [
                unit
                for unit in units
                if unit.verse_devanagari.strip() and unit.has_translation
            ]

            # Stratify. Sorting purely by risk returns units that are *all*
            # grouped-and-page-spanning, which leaves the ordinary path — one
            # verse, one page — completely unguarded. A gate has to catch a
            # regression in the common case too.
            risky = sorted(
                (
                    unit
                    for unit in complete
                    if (unit.verse_ref_local and "-" in unit.verse_ref_local)
                    or unit.page_from != unit.page_to
                ),
                key=_interest,
            )
            simple = sorted(
                (
                    unit
                    for unit in complete
                    if not (unit.verse_ref_local and "-" in unit.verse_ref_local)
                    and unit.page_from == unit.page_to
                ),
                key=_interest,
            )
            simple_quota = args.per_volume // 3
            selected = risky[: args.per_volume - simple_quota] + simple[:simple_quota]

            for unit in selected:
                entries.append(
                    {
                        "book": slug,
                        "chapter": unit.chapter,
                        "verse_ref_local": unit.verse_ref_local,
                        "verse_devanagari": unit.verse_devanagari,
                        "translation": unit.translation,
                        "commentary": unit.commentary,
                        "page_from": unit.page_from,
                        "page_to": unit.page_to,
                        "inferred_verse_no": unit.inferred_verse_no,
                    }
                )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps({"units": entries}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    ranged = sum(1 for e in entries if "-" in (e["verse_ref_local"] or ""))
    spanning = sum(1 for e in entries if e["page_from"] != e["page_to"])
    simple = sum(
        1
        for e in entries
        if "-" not in (e["verse_ref_local"] or "") and e["page_from"] == e["page_to"]
    )
    vol2_danda = sum(1 for e in entries if _DANDA_VOL2 in e["verse_devanagari"])
    print(f"wrote {len(entries)} candidate units to {OUT}")
    print(
        f"  grouped ranges: {ranged} | page-spanning: {spanning} "
        f"| simple single-page: {simple} | vol2 danda: {vol2_danda}"
    )
    print("NOW HAND-CHECK THEM against the scanned pages before trusting the gate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
