"""M1's hard gate: a verse must never be separated from its meaning.

This is the pipeline's most dangerous silent failure. A verse attached to the
wrong translation still retrieves, still cites, and still reads fluently — nothing
about the output looks broken, and every rule later extracted from it inherits
correct-looking provenance for the wrong verse. Hence zero tolerance, not a
percentage.

The fixture is hand-checked against the scanned pages. It has to be: a fixture
generated by the code it tests only proves the code is self-consistent.
"""

import json
from pathlib import Path

import pytest

from rishivan.knowledge.reflow import adjacency_violations
from rishivan.knowledge.schemas.unit import SutraUnitDraft

GOLDEN = Path(__file__).parents[2] / "golden" / "bphs_adjacency.json"

MIN_UNITS = 100
_DANDA_VOL2 = "।।"

_DRAFT_FIELDS = (
    "verse_devanagari",
    "verse_iast",
    "translation",
    "commentary",
    "chapter",
    "verse_ref_local",
    "inferred_verse_no",
    "page_from",
    "page_to",
)


@pytest.fixture(scope="module")
def payload() -> dict:
    if not GOLDEN.exists():
        pytest.fail(
            f"{GOLDEN} is missing — run `uv run python -m scripts.build_golden_units` "
            f"and hand-check the result. A skipped gate passes vacuously, which is "
            f"exactly the state this gate exists to make impossible."
        )
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def golden_units(payload) -> list[SutraUnitDraft]:
    return [
        SutraUnitDraft(**{key: entry[key] for key in _DRAFT_FIELDS if key in entry})
        for entry in payload["units"]
    ]


def test_golden_set_is_large_enough_and_covers_both_volumes(payload):
    units = payload["units"]
    assert len(units) >= MIN_UNITS
    assert {entry["book"] for entry in units} == {
        "bphs-gcsharma-vol1",
        "bphs-gcsharma-vol2",
    }


def test_golden_set_covers_the_cases_that_break(payload):
    """A random sample would be mostly easy single verses, and a broken bridge
    would pass it."""
    units = payload["units"]

    # Grouped verse ranges — the merge path.
    assert any("-" in (entry["verse_ref_local"] or "") for entry in units)
    # Units spanning a page boundary — reflow surviving a running head.
    assert any(entry["page_from"] != entry["page_to"] for entry in units)
    # Vol 2's two-single-danda delimiter.
    assert any(_DANDA_VOL2 in entry["verse_devanagari"] for entry in units)
    # At least one verse number actually read rather than counted.
    assert any(entry["inferred_verse_no"] is False for entry in units)


def test_golden_set_also_covers_the_ordinary_path(payload):
    """Stratified on purpose: a gate made only of hard cases leaves the common
    case — one verse, one page — unguarded."""
    simple = [
        entry
        for entry in payload["units"]
        if "-" not in (entry["verse_ref_local"] or "")
        and entry["page_from"] == entry["page_to"]
    ]
    assert len(simple) >= 20


def test_zero_adjacency_violations(golden_units):
    assert adjacency_violations(golden_units) == []


def test_every_golden_unit_has_both_a_verse_and_a_meaning(golden_units):
    for unit in golden_units:
        assert unit.verse_devanagari.strip(), f"{unit.verse_ref_local} lost its verse"
        assert unit.has_translation, f"{unit.verse_ref_local} lost its translation"


def test_no_ingestion_labels_leaked_into_the_text(golden_units):
    """`[Heading: ...]` and `Original Content:` are the POC extractor's own labels,
    not the book's. Leaking one into a verse corrupts every citation quoting it."""
    for unit in golden_units:
        for field in (unit.verse_devanagari, unit.translation, unit.commentary):
            assert "[Heading:" not in field
            assert "Original Content:" not in field


def test_devanagari_and_english_refs_agree(golden_units):
    """Independent corroboration, and the strongest signal in this file.

    A unit's ref comes from Devanagari markers in the shloka; the translation
    carries its own label in Latin digits. Two separate readings of the same
    number, so agreement is evidence the pairing is right that does not come from
    the pairing code. Measured across the whole corpus: 963 checkable units,
    96.99% agreement, and the 29 disagreements are mostly the OCR confusing
    Devanagari १ with ९. The golden set is hand-checked, so here it must be 100%.
    """
    from rishivan.knowledge.bridge.verse_ref import verse_ref_from_translation

    mismatches = [
        (unit.verse_ref_local, verse_ref_from_translation(unit.translation))
        for unit in golden_units
        if verse_ref_from_translation(unit.translation) is not None
        and verse_ref_from_translation(unit.translation) != unit.verse_ref_local
    ]
    assert mismatches == [], f"Devanagari/English ref disagreement: {mismatches}"


def test_enough_units_carry_an_independent_english_label(golden_units):
    """Vol 2 rarely labels its translations, so the cross-check can only run on a
    subset. Guard that the subset stays big enough to be meaningful."""
    from rishivan.knowledge.bridge.verse_ref import verse_ref_from_translation

    checkable = sum(
        1
        for unit in golden_units
        if verse_ref_from_translation(unit.translation) is not None
    )
    assert checkable >= 30
